/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mice.interactive;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author pemo
 */
public class AndraProjekt extends javax.swing.JFrame {

    private InfDB databasen;
    private DatabaseManager dbManager;
    /**
     * Creates new form laggTillProjekt
     */
    public AndraProjekt() {
        
        dbManager = new DatabaseManager();
        try {
            databasen = new InfDB("C:\\Program Files\\databasen\\MICEDB.FDB");
       
        } catch (InfException ex) {
            Logger.getLogger(Sokpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setFyllProject();
        fyllAnstalld();
        fyllLedare();
        fyllDatumBoxar();
        fyllPlattform();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Overpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ValjProjektPanel = new javax.swing.JPanel();
        combChangeProject = new javax.swing.JComboBox();
        ValtProjektPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblProjectLeaderName = new javax.swing.JLabel();
        lblProjektbeskrivning = new javax.swing.JLabel();
        LblProjektNamn = new javax.swing.JLabel();
        lblStartDatumbeskrivning = new javax.swing.JLabel();
        lblslutdatumbeskrivning = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProjektJobbare = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPlattformar = new javax.swing.JList();
        ValjAnstalldPanel = new javax.swing.JPanel();
        combAndraAnstalld = new javax.swing.JComboBox();
        jbnLäggTillAnställd = new javax.swing.JButton();
        jbnTaBortAnstalld = new javax.swing.JButton();
        SattLedarePanel = new javax.swing.JPanel();
        combSetLeader = new javax.swing.JComboBox();
        jbnSattNyLedare = new javax.swing.JButton();
        SattDatumPanel = new javax.swing.JPanel();
        combStartAr = new javax.swing.JComboBox();
        combStartManad = new javax.swing.JComboBox();
        combStartDag = new javax.swing.JComboBox();
        jbnSattStartdatum = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        combSlutAr = new javax.swing.JComboBox();
        combSlutManad = new javax.swing.JComboBox();
        combSlutDag = new javax.swing.JComboBox();
        jbnSattSlutdatum = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        combPlattformar = new javax.swing.JComboBox();
        jbnTaBortProjekt = new javax.swing.JButton();
        jbnLaggTillPlattform = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jbnSystemMeny = new javax.swing.JButton();
        jbnLäggTillProjekt = new javax.swing.JButton();
        jbnVisaProjekt = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jbnSättNamn = new javax.swing.JButton();
        txtProjektNamn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Uppdatera Projekt");

        ValjProjektPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Välj projekt"));

        combChangeProject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combChangeProject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combChangeProjectItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout ValjProjektPanelLayout = new javax.swing.GroupLayout(ValjProjektPanel);
        ValjProjektPanel.setLayout(ValjProjektPanelLayout);
        ValjProjektPanelLayout.setHorizontalGroup(
            ValjProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValjProjektPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combChangeProject, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        ValjProjektPanelLayout.setVerticalGroup(
            ValjProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValjProjektPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combChangeProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ValtProjektPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Valt Projekt"));

        jLabel9.setText("Ledare:");

        lblProjectLeaderName.setText("<none>");

        lblProjektbeskrivning.setText("Projektnamn:");

        LblProjektNamn.setText("<none>");

        lblStartDatumbeskrivning.setText("Startdatum:");

        lblslutdatumbeskrivning.setText("Slutdatum:");

        lblStartdatum.setText("<none>");

        lblSlutdatum.setText("<none>");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Jobbar i projekt"));

        jScrollPane2.setViewportView(jListProjektJobbare);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Plattformar"));

        jScrollPane1.setViewportView(jListPlattformar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ValtProjektPanelLayout = new javax.swing.GroupLayout(ValtProjektPanel);
        ValtProjektPanel.setLayout(ValtProjektPanelLayout);
        ValtProjektPanelLayout.setHorizontalGroup(
            ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValtProjektPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ValtProjektPanelLayout.createSequentialGroup()
                        .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ValtProjektPanelLayout.createSequentialGroup()
                                .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ValtProjektPanelLayout.createSequentialGroup()
                                        .addComponent(lblProjektbeskrivning)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ValtProjektPanelLayout.createSequentialGroup()
                                        .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblslutdatumbeskrivning, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LblProjektNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(lblSlutdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProjectLeaderName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(ValtProjektPanelLayout.createSequentialGroup()
                                .addComponent(lblStartDatumbeskrivning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(lblStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ValtProjektPanelLayout.setVerticalGroup(
            ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValtProjektPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektbeskrivning)
                    .addComponent(LblProjektNamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDatumbeskrivning)
                    .addComponent(lblStartdatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblslutdatumbeskrivning)
                    .addComponent(lblSlutdatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ValtProjektPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblProjectLeaderName))
                .addGap(262, 262, 262))
            .addGroup(ValtProjektPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        ValjAnstalldPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Välj anställd"));

        combAndraAnstalld.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbnLäggTillAnställd.setText("lägg till");
        jbnLäggTillAnställd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnLäggTillAnställdActionPerformed(evt);
            }
        });

        jbnTaBortAnstalld.setText("Ta bort");
        jbnTaBortAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnTaBortAnstalldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ValjAnstalldPanelLayout = new javax.swing.GroupLayout(ValjAnstalldPanel);
        ValjAnstalldPanel.setLayout(ValjAnstalldPanelLayout);
        ValjAnstalldPanelLayout.setHorizontalGroup(
            ValjAnstalldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValjAnstalldPanelLayout.createSequentialGroup()
                .addComponent(combAndraAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnLäggTillAnställd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbnTaBortAnstalld))
        );
        ValjAnstalldPanelLayout.setVerticalGroup(
            ValjAnstalldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValjAnstalldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combAndraAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValjAnstalldPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ValjAnstalldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnTaBortAnstalld)
                    .addComponent(jbnLäggTillAnställd)))
        );

        SattLedarePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Välj ledare"));

        combSetLeader.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbnSattNyLedare.setText("Sätt ny ledare");
        jbnSattNyLedare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSattNyLedareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SattLedarePanelLayout = new javax.swing.GroupLayout(SattLedarePanel);
        SattLedarePanel.setLayout(SattLedarePanelLayout);
        SattLedarePanelLayout.setHorizontalGroup(
            SattLedarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SattLedarePanelLayout.createSequentialGroup()
                .addComponent(combSetLeader, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnSattNyLedare))
        );
        SattLedarePanelLayout.setVerticalGroup(
            SattLedarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SattLedarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combSetLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SattLedarePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbnSattNyLedare))
        );

        SattDatumPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Välj Startdatum"));

        combStartAr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combStartManad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combStartManad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combStartManadItemStateChanged(evt);
            }
        });

        combStartDag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbnSattStartdatum.setText("Sätt Datum");
        jbnSattStartdatum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnSattStartdatumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SattDatumPanelLayout = new javax.swing.GroupLayout(SattDatumPanel);
        SattDatumPanel.setLayout(SattDatumPanelLayout);
        SattDatumPanelLayout.setHorizontalGroup(
            SattDatumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SattDatumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combStartAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combStartManad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combStartDag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnSattStartdatum))
        );
        SattDatumPanelLayout.setVerticalGroup(
            SattDatumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SattDatumPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(SattDatumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combStartAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combStartManad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combStartDag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SattDatumPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbnSattStartdatum))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Välj Slutdatum"));

        combSlutAr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combSlutManad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combSlutManad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combSlutManadItemStateChanged(evt);
            }
        });

        combSlutDag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbnSattSlutdatum.setText("Sätt Datum");
        jbnSattSlutdatum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnSattSlutdatumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combSlutAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combSlutManad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combSlutDag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnSattSlutdatum))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combSlutAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combSlutManad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combSlutDag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbnSattSlutdatum))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Välj Plattformar"));

        combPlattformar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbnTaBortProjekt.setText("Ta Bort");
        jbnTaBortProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnTaBortProjektMouseClicked(evt);
            }
        });

        jbnLaggTillPlattform.setText("Lägg Till");
        jbnLaggTillPlattform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnLaggTillPlattformMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combPlattformar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnLaggTillPlattform)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbnTaBortProjekt))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combPlattformar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnTaBortProjekt)
                    .addComponent(jbnLaggTillPlattform)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gå till"));

        jbnSystemMeny.setText("System meny");
        jbnSystemMeny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnSystemMenyMouseClicked(evt);
            }
        });

        jbnLäggTillProjekt.setText("Lägg till projekt");
        jbnLäggTillProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnLäggTillProjektMouseClicked(evt);
            }
        });

        jbnVisaProjekt.setText("Visa projekt");
        jbnVisaProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnVisaProjektMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jbnSystemMeny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbnLäggTillProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbnVisaProjekt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnSystemMeny)
                    .addComponent(jbnLäggTillProjekt)
                    .addComponent(jbnVisaProjekt))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sätt nytt projektnamn"));

        jbnSättNamn.setText("Sätt Namn");
        jbnSättNamn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnSättNamnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbnSättNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbnSättNamn))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout OverpanelLayout = new javax.swing.GroupLayout(Overpanel);
        Overpanel.setLayout(OverpanelLayout);
        OverpanelLayout.setHorizontalGroup(
            OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OverpanelLayout.createSequentialGroup()
                        .addComponent(ValtProjektPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(OverpanelLayout.createSequentialGroup()
                        .addComponent(ValjProjektPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
            .addGroup(OverpanelLayout.createSequentialGroup()
                .addGroup(OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SattDatumPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SattLedarePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValjAnstalldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        OverpanelLayout.setVerticalGroup(
            OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverpanelLayout.createSequentialGroup()
                .addGroup(OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OverpanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ValjProjektPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OverpanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addGap(40, 40, 40)
                .addComponent(ValtProjektPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SattLedarePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ValjAnstalldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SattDatumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OverpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(Overpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Overpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combChangeProjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combChangeProjectItemStateChanged
        displayProjectInfo();
    }//GEN-LAST:event_combChangeProjectItemStateChanged

    private void jbnTaBortAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnTaBortAnstalldActionPerformed
        if(combChangeProject.getSelectedItem().toString().equals("Byt Projekt <inget valt>"))
        {
              
            JOptionPane.showMessageDialog(rootPane, "Välj ett projekt att ta bort nån från");
            return;
        }
        if(combAndraAnstalld.getSelectedItem().toString().equals("<none>"))
        {
            JOptionPane.showMessageDialog(rootPane, "Välj en anställd att ta bort");
            return;
        }
        boolean finnsI = false;
        ListModel model = jListProjektJobbare.getModel();
        for( int i = 0; i < model.getSize(); i++)
        {
            if (model.getElementAt(i).toString().equals(combAndraAnstalld.getSelectedItem().toString()))
            {
                finnsI = true;
            }

        }
        if (finnsI)
        {
        String anvNamn = 
                Hjalpklass.konverteraListItemTillAnvNamn(combAndraAnstalld.getSelectedItem().toString());
        
//        String anvnamn = valdAnstalld.substring((valdAnstalld.indexOf("(") + 1),
//            valdAnstalld.indexOf(")"));
        String valtProjekt = combChangeProject.getSelectedItem().toString();

        String aid = konverteraTillAid(anvNamn);
        String sid = konverteraTillSid(valtProjekt);

        String query = "delete from ARBETAR_I where AID =" + " '" + aid + "' and SID" + "= '" + sid + "';";

        try {
            databasen.delete(query);
        }
        catch (InfException ex)
        {
        }
        setAnstalldaIProjekt();
        }
        
        else
        {  
            JOptionPane.showMessageDialog(rootPane, "Kan ju inte ta bort nån som inte jobbar vettu");
            finnsI = false;
            return;
        }
    }//GEN-LAST:event_jbnTaBortAnstalldActionPerformed

    private void jbnLäggTillAnställdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnLäggTillAnställdActionPerformed

        if(LblProjektNamn.getText().equals("<none>"))
        {
            JOptionPane.showMessageDialog(null, "Välj ett Projekt du kan lägga till en anställd för");
            return;
        }
        
        if(combAndraAnstalld.getSelectedItem().toString().equals("<none>"))
        {
            JOptionPane.showMessageDialog(null, "Välj en anställd");
            return;
        }
        boolean finnsI = false;
        ListModel model = jListProjektJobbare.getModel();
        for( int i = 0; i < model.getSize(); i++)
        {
            if(model.getElementAt(i).toString().equals(combAndraAnstalld.getSelectedItem().toString()))
            {
                finnsI = true;
            }

        }
        if (finnsI)
        {
            JOptionPane.showMessageDialog(null, "Den anställde jobbar redan i projektet");
            return;
        }
        String valdAnstalld = combAndraAnstalld.getSelectedItem().toString();
        String anvnamn = valdAnstalld.substring((valdAnstalld.indexOf("(") + 1),
            valdAnstalld.indexOf(")"));
        String valtProjekt = combChangeProject.getSelectedItem().toString();

        String aid = konverteraTillAid(anvnamn);
        String sid = konverteraTillSid(valtProjekt);

        String query = "insert into ARBETAR_I (AID, SID) values('" + aid + "','" + sid + "');";
        
        
        try {
            databasen.insert(query);
        }
        catch (InfException ex)
        {
        }
        setAnstalldaIProjekt();

    }//GEN-LAST:event_jbnLäggTillAnställdActionPerformed

    private void jbnSattNyLedareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSattNyLedareActionPerformed
    
        if(combSetLeader.getSelectedItem().toString().equals("<Välj ny ledare>"))
        {
            JOptionPane.showMessageDialog(rootPane, "Du måste välja ut en ny ledare ur boxen Välj ny ledare!");
            return;
        
        }
        
        if(combSetLeader.getSelectedItem().toString().equals(lblProjectLeaderName.getText()))
        
        {
            JOptionPane.showMessageDialog(null, "Du bör nog välja en ledare som inte redan är ledare för projektet");
            return;
        }
       
        String valdledare = combSetLeader.getSelectedItem().toString();
        String anvnamn = valdledare.substring((valdledare.indexOf("(") + 1),
            valdledare.indexOf(")"));
        String spel = combChangeProject.getSelectedItem().toString();
        String aid = konverteraTillAid(anvnamn);
        String query = "UPDATE SPELPROJEKT SET AID = '" + aid + "' where Spelprojekt.beteckning = '" + spel + "';";
        try {
            databasen.update(query);
            lblProjectLeaderName.setText(databasen.fetchSingle("SELECT ANSTALLD.NAMN FROM ANSTALLD WHERE AID = (SELECT AID FROM SPELPROJEKT WHERE BETECKNING = '" + spel + "');"));
        } catch (InfException ex) {
            Logger.getLogger(AndraProjekt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jbnSattNyLedareActionPerformed

    private void jbnSattStartdatumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnSattStartdatumMouseClicked
         String startDatum = combStartAr.getSelectedItem().toString()
        + "-" + Hjalpklass.getManadsNummer(combStartManad.getSelectedItem().toString())
        + "-" + combStartDag.getSelectedItem().toString();
        
         if(lblSlutdatum.getText() == null || lblSlutdatum.getText().equals("<none>"))
        {
            updateStartDatum(startDatum);
        }
        else
        {
            String slutDatum = lblSlutdatum.getText();
            if(Validering.jamforStartvsSlutDatum(startDatum, slutDatum))

                {
                    JOptionPane.showMessageDialog(null, "Projektet kan inte sluta innan det startar");
                    return;
                }
            updateStartDatum(startDatum);
        }
         
    }//GEN-LAST:event_jbnSattStartdatumMouseClicked

    private void updateStartDatum(String datum) {

        String spel = combChangeProject.getSelectedItem().toString();
        if(spel.equals("Byt Projekt <inget valt>"))
        {
            JOptionPane.showMessageDialog(null, "Du har inte valt något projekt att sätta datum på");
            return;
        }    
        dbManager.updateStartDatum(datum, spel);
        lblStartdatum.setText(datum);
    }
    
    private void jbnSattSlutdatumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnSattSlutdatumMouseClicked
      String slutDatum = combSlutAr.getSelectedItem().toString()
        + "-" + Hjalpklass.getManadsNummer(combSlutManad.getSelectedItem().toString())
        + "-" + combSlutDag.getSelectedItem().toString();
        
        
        if(lblStartdatum.getText() == null || lblStartdatum.getText().equals("<none>"))
        {
            updateSlutDatum(slutDatum);
        }
        else
        {
            String startDatum = lblStartdatum.getText();
            if(Validering.jamforStartvsSlutDatum(startDatum, slutDatum))

                {
                    JOptionPane.showMessageDialog(null, "Projektet kan inte sluta innan det startar");
                    return;
                }
            updateSlutDatum(slutDatum);
        }

    }//GEN-LAST:event_jbnSattSlutdatumMouseClicked

    private void updateSlutDatum(String datum) {
        
        String spel = combChangeProject.getSelectedItem().toString();
                if(spel.equals("Byt Projekt <inget valt>"))
        {
            JOptionPane.showMessageDialog(null, "Du har inte valt något projekt att sätta datum på");
            return;
        }    
        
        dbManager.updateSlutDatum(datum, spel);
        lblSlutdatum.setText(datum);
    }

    private void jbnLaggTillPlattformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnLaggTillPlattformMouseClicked
      
        if(LblProjektNamn.getText().equals("<none>"))
        {
            JOptionPane.showMessageDialog(null, "Välj ett projekt att lägga till en plattform för");
            return;
        }
        
        if(combPlattformar.getSelectedItem().toString().equals("<none>"))
        {
            JOptionPane.showMessageDialog(null, "Välj en plattform");
            return;
        }
        boolean finnsI = false;
        ListModel model = jListPlattformar.getModel();
        for( int i = 0; i < model.getSize(); i++)
        {
            if(model.getElementAt(i).toString().equals(combPlattformar.getSelectedItem().toString()))
            {
                finnsI = true;
            }

            
        }
        if (finnsI)
        {
            JOptionPane.showMessageDialog(null, "Projektet uvecklas redan för plattformen");
            return;
        }
        String valdPlattform = combPlattformar.getSelectedItem().toString();
 
        String valtProjekt = combChangeProject.getSelectedItem().toString();

        String pid = konverteraTillPlattform(valdPlattform);
        String sid = konverteraTillSid(valtProjekt);

        String query = "insert into INNEFATTAR (SID, PID) values ('" + sid + "','" + pid + "');";
        
        
        try {
            databasen.insert(query);
        }
        catch (InfException ex)
        {
        }
        setPlattformList();
    }//GEN-LAST:event_jbnLaggTillPlattformMouseClicked

    private void jbnTaBortProjektMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnTaBortProjektMouseClicked
     if(combChangeProject.getSelectedItem().toString().equals("Byt Projekt <inget valt>"))
        {
              
            JOptionPane.showMessageDialog(rootPane, "Välj ett projekt att ta bort nån från");
            return;
        }
        if(combPlattformar.getSelectedItem().toString().equals("<none>"))
        {
            JOptionPane.showMessageDialog(rootPane, "Välj en plattform att ta bort");
            return;
        }
        
        boolean finnsI = false;
        ListModel model = jListPlattformar.getModel();
        for( int i = 0; i < model.getSize(); i++)
        {
            if (model.getElementAt(i).toString().equals(combPlattformar.getSelectedItem().toString()))
            {
                finnsI = true;
            }

        }
        if (finnsI)
        {
        String valdPlattform = combPlattformar.getSelectedItem().toString();
        String valtProjekt = combChangeProject.getSelectedItem().toString();

        String pid = konverteraTillPlattform(valdPlattform);
        String sid = konverteraTillSid(valtProjekt);

        String query = "delete from INNEFATTAR where SID =" + " '" + sid + "' and PID" + "= '" + pid + "';";

        try {
            databasen.delete(query);
        }
        catch (InfException ex)
        {
        }
        setPlattformList();
        }
        
        else
        {  
            JOptionPane.showMessageDialog(rootPane, "Kan ju inte ta bort nått som inte existerar");
            finnsI = false;
            return;
        }
    }//GEN-LAST:event_jbnTaBortProjektMouseClicked

    private void combStartManadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combStartManadItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            Hjalpklass.fyllDagar(combStartDag, combStartManad.getSelectedItem().toString());
        }
    }//GEN-LAST:event_combStartManadItemStateChanged

    private void combSlutManadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combSlutManadItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            Hjalpklass.fyllDagar(combSlutDag, combSlutManad.getSelectedItem().toString());
        }
        
    }//GEN-LAST:event_combSlutManadItemStateChanged

    private void jbnSystemMenyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnSystemMenyMouseClicked
        // TODO add your handling code here:
        Inloggad InloggadFrame = new Inloggad(); 
        InloggadFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnSystemMenyMouseClicked

    private void jbnLäggTillProjektMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnLäggTillProjektMouseClicked
        // TODO add your handling code here:
        LaggTillSpelProjekt LaggTillSpelProjektFrame = new LaggTillSpelProjekt();
        LaggTillSpelProjektFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnLäggTillProjektMouseClicked

    private void jbnSättNamnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnSättNamnMouseClicked
        // TODO add your handling code here:
        String matchning = txtProjektNamn.getText();
        {
            
            dbManager.getSpelprojektnamnLista();
            ArrayList<String> spelprojekt = dbManager.getSpelprojektnamnLista();
            if(Validering.emptyString(txtProjektNamn.getText()))

            {
                JOptionPane.showMessageDialog(null, "Saknas projektnamn");
                return;
            }
            
             if(spelprojekt.contains(matchning) && LblProjektNamn.getText().equals("<none>"))
            {

                JOptionPane.showMessageDialog(null, "Finns redan ett Projekt med det namnet");
                return;
            }
           
            if(spelprojekt.contains(matchning))
            {
                JOptionPane.showMessageDialog(null, "Döp om projektet om du ska uppdatera det");
                return;

            }
            if(LblProjektNamn.getText().equals("<none>"))
            {
                JOptionPane.showMessageDialog(null, "Välj ett Projekt att ändra namn på");
                return;
            }
            String Namn = dbManager.konverteraTillSid(LblProjektNamn.getText());
            dbManager.setNyttProjektNamn(matchning, Namn);
            LblProjektNamn.setText(txtProjektNamn.getText());
            AndraProjekt AndraProjektFrame = new AndraProjekt(); 
            AndraProjektFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbnSättNamnMouseClicked

    private void jbnVisaProjektMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnVisaProjektMouseClicked
        // TODO add your handling code here:
        VisaProjekt VisaProjektFrame = new VisaProjekt();
        VisaProjektFrame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jbnVisaProjektMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblProjektNamn;
    private javax.swing.JPanel Overpanel;
    private javax.swing.JPanel SattDatumPanel;
    private javax.swing.JPanel SattLedarePanel;
    private javax.swing.JPanel ValjAnstalldPanel;
    private javax.swing.JPanel ValjProjektPanel;
    private javax.swing.JPanel ValtProjektPanel;
    private javax.swing.JComboBox combAndraAnstalld;
    private javax.swing.JComboBox combChangeProject;
    private javax.swing.JComboBox combPlattformar;
    private javax.swing.JComboBox combSetLeader;
    private javax.swing.JComboBox combSlutAr;
    private javax.swing.JComboBox combSlutDag;
    private javax.swing.JComboBox combSlutManad;
    private javax.swing.JComboBox combStartAr;
    private javax.swing.JComboBox combStartDag;
    private javax.swing.JComboBox combStartManad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListPlattformar;
    private javax.swing.JList jListProjektJobbare;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbnLaggTillPlattform;
    private javax.swing.JButton jbnLäggTillAnställd;
    private javax.swing.JButton jbnLäggTillProjekt;
    private javax.swing.JButton jbnSattNyLedare;
    private javax.swing.JButton jbnSattSlutdatum;
    private javax.swing.JButton jbnSattStartdatum;
    private javax.swing.JButton jbnSystemMeny;
    private javax.swing.JButton jbnSättNamn;
    private javax.swing.JButton jbnTaBortAnstalld;
    private javax.swing.JButton jbnTaBortProjekt;
    private javax.swing.JButton jbnVisaProjekt;
    private javax.swing.JLabel lblProjectLeaderName;
    private javax.swing.JLabel lblProjektbeskrivning;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartDatumbeskrivning;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblslutdatumbeskrivning;
    private javax.swing.JTextField txtProjektNamn;
    // End of variables declaration//GEN-END:variables

    private void setFyllProject() {
        
        String query = "SELECT BETECKNING FROM SPELPROJEKT ORDER BY BETECKNING ASC";
        try {
            
            combChangeProject.removeAllItems();
            ArrayList<String> projekten = databasen.fetchColumn(query);
            combChangeProject.addItem("Byt Projekt <inget valt>");
            for(String projekt : projekten)
            {
                combChangeProject.addItem(projekt);
                
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    private void fyllLedare() {
        String query = "SELECT ANSTALLD.NAMN, ANSTALLD.ANVNAMN FROM PROJEKTLEDARE\n" +
                       "JOIN ANSTALLD ON PROJEKTLEDARE.AID = ANSTALLD.AID\n" +
                       "ORDER BY NAMN ASC";
        try {
            
            combSetLeader.removeAllItems();
            ArrayList<HashMap<String,String>> ledarLista = new ArrayList<>();
            ledarLista = databasen.fetchRows(query);
            combSetLeader.addItem("<Välj ny ledare>");
            for(HashMap<String,String> ledare : ledarLista)
            {
                String enLedare = ledare.get("NAMN") + " (" + ledare.get("ANVNAMN") + ")";
                combSetLeader.addItem(enLedare);
                
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    private void fyllPlattform()
    
    {
        
        combPlattformar.removeAllItems();
        Hjalpklass.fyllVilkenComboSomHelst(combPlattformar, dbManager.getPlattformlista());
        combPlattformar.insertItemAt("<none>", 0);
        combPlattformar.setSelectedIndex(0);
    }
    
        private void fyllAnstalld() {
        
            
        
        
        Hjalpklass.fyllVilkenComboSomHelst(combAndraAnstalld, dbManager.getAnstalldLista());
        
        combAndraAnstalld.insertItemAt("<none>", 0);
        combAndraAnstalld.setSelectedIndex(0);
        
        
    }
    private void displayProjectInfo()
    {
        jListProjektJobbare.setModel(new DefaultListModel());
        jListPlattformar.setModel(new DefaultListModel());
        
       if( setProjectNamelabel())
       {
         setProjectLeaderName();
         setAnstalldaIProjekt();
         setPlattformList();
         setProjectStartdate();
         setProjectEnddate();
         
        
       }
        
        
           
    }

    private boolean setProjectNamelabel() {
        
        int selectedIndex = combChangeProject.getSelectedIndex();
        if (selectedIndex == -1) {
            return false;
        }
        if (selectedIndex == 0) {
            LblProjektNamn.setText("<none>");
            lblProjectLeaderName.setText("<none>");
            lblStartdatum.setText("<none>");
            lblSlutdatum.setText("<none>");
            return false;
        }
        String selectedProject = combChangeProject.getSelectedItem().toString();
        LblProjektNamn.setText(selectedProject);
        return true;
       
    }

    private void setProjectLeaderName() 
    {
        
        try {
            String spelprojekt = combChangeProject.getSelectedItem().toString();
            String query = "SELECT ANSTALLD.NAMN FROM PROJEKTLEDARE " +
                    "JOIN ANSTALLD ON PROJEKTLEDARE.AID = ANSTALLD.AID " +
                    "JOIN SPELPROJEKT ON PROJEKTLEDARE.AID = SPELPROJEKT.AID "
                    + "WHERE SPELPROJEKT.BETECKNING = '" + spelprojekt + "'";
            
            String ledare = databasen.fetchSingle(query);
            if(ledare == null)
            {
                lblProjectLeaderName.setText("<none>");
            }
            else
            {
                lblProjectLeaderName.setText(ledare);
            }
        } catch (InfException ex) {
        }
    }

    private void setAnstalldaIProjekt() 
    {
    try {
        DefaultListModel DLM = new DefaultListModel();
        String spelprojekt = combChangeProject.getSelectedItem().toString();
        String query = "SELECT ANSTALLD.NAMN, ANSTALLD.ANVNAMN FROM ANSTALLD join ARBETAR_I on ANSTALLD.AID = ARBETAR_I.AID"
                     + " JOIN SPELPROJEKT on ARBETAR_I.SID = SPELPROJEKT.SID "
                     + "WHERE SPELPROJEKT.BETECKNING = '" + spelprojekt + "'";
            ArrayList<HashMap<String,String>> anstallda = new ArrayList<>();
            anstallda = databasen.fetchRows(query);
            if(anstallda != null)
            {
                for(HashMap<String,String> anstalld : anstallda)
                {
                    String enAnstalld = anstalld.get("NAMN")+ " (" + anstalld.get("ANVNAMN") + ")";
                    DLM.addElement(enAnstalld);
                }
            
            
            
            }
            jListProjektJobbare.setModel(DLM);

        }
        catch (InfException ex) 
                {
                JOptionPane.showMessageDialog(null, "bajs!" + ex.getMessage());
                }
            
        
    }
    private void setPlattformList()
    {
         try {
        DefaultListModel DLM = new DefaultListModel();
        String spelprojekt = combChangeProject.getSelectedItem().toString();
        String query = "SELECT PLATTFORM.BENAMNING FROM INNEFATTAR" 
        + " join PLATTFORM on INNEFATTAR.PID = PLATTFORM.PID"
        + " join SPELPROJEKT on INNEFATTAR.SID = SPELPROJEKT.SID"        
        + " WHERE INNEFATTAR.SID = (SELECT SID FROM SPELPROJEKT WHERE BETECKNING = '" + spelprojekt + "');";
            ArrayList<String> plattformar = new ArrayList<>();
            plattformar = databasen.fetchColumn(query);
            if(plattformar != null)
            {
                for (String plattform : plattformar)
                {
                    DLM.addElement(plattform);
                }
            
            jListPlattformar.setModel(DLM);
            }
            else
            {
                jListPlattformar.setModel(DLM);
                setProjectStartdate();
            }
        } 
    catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "fel!" + ex.getMessage());
        }
    }
    private String konverteraTillAid(String anvNamn)
    {
        
        String aid = "";
        
       
        String query = "SELECT AID FROM ANSTALLD WHERE ANVNAMN = '" + anvNamn + "'";
        try{
            aid = databasen.fetchSingle(query);
        }
        catch(InfException ex)
        {
            System.out.println("BLÄV FÄL!");
        }
        
        
        return aid;
    }
    private String konverteraTillSid(String valtProject)
    { 
        String sid = "";
        try {
           
            String query = "SELECT SPELPROJEKT.SID FROM SPELPROJEKT where BETECKNING = '" + valtProject + "'";
            sid = databasen.fetchSingle(query);
            }
            catch (InfException ex) 
             {
             }
        return sid;
            
     } 
    private String konverteraTillPlattform(String valdPlattform)
    {
        String pid = "";
        try {
           
            String query = "SELECT PlATTFORM.PID FROM PLATTFORM where BENAMNING = '" + valdPlattform + "'";
            pid = databasen.fetchSingle(query);
            }
            catch (InfException ex) 
             {
             }
        return pid;
    }

    private void setProjectStartdate() {
        try {
            String spelprojekt = combChangeProject.getSelectedItem().toString();
            String query = "SELECT STARTDATUM FROM SPELPROJEKT"
                    + " WHERE SPELPROJEKT.BETECKNING = '" + spelprojekt + "'";
            
            String datum = databasen.fetchSingle(query);
            if(datum != null){
            lblStartdatum.setText(datum);
            }
            else
            {
                lblStartdatum.setText("<none>");
            }
        } catch (InfException ex) {
        }
    }

    private void setProjectEnddate() {
        
        try {
            String spelprojekt = combChangeProject.getSelectedItem().toString();
            String query = "SELECT RELEASEDATUM FROM SPELPROJEKT"
                    + " WHERE SPELPROJEKT.BETECKNING = '" + spelprojekt + "'";
            
            String datum = databasen.fetchSingle(query);
            if(datum != null){
            lblSlutdatum.setText(datum);
            }
            else
            {
                lblSlutdatum.setText("<none>");
            }
        } catch (InfException ex) {
        }
    }
    private void fyllDatumBoxar() {
        
        Hjalpklass.fyllAr(combStartAr, 2006, 2025);
        Hjalpklass.fyllManader(combStartManad);
        Hjalpklass.fyllDagar(combStartDag, "Jan");
        
        Hjalpklass.fyllAr(combSlutAr, 2006, 2025);
        Hjalpklass.fyllManader(combSlutManad);
        Hjalpklass.fyllDagar(combSlutDag, "Jan");
        
    }

}