/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mice.interactive;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author pemo
 */
public class laggTillProjekt extends javax.swing.JFrame {

    private InfDB databasen;
    /**
     * Creates new form laggTillProjekt
     */
    public laggTillProjekt() {
        try {
            databasen = new InfDB("C:\\Program Files\\databasen\\MICEDB.FDB");
       
        } catch (InfException ex) {
            Logger.getLogger(Sokpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setFyllProject();
        setFyllLedare();
        fyllAnstalld();
        fyllLedare();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        LabelÖverskrift = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LblProjektNamn = new javax.swing.JLabel();
        combChangeProject = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProjektJobbare = new javax.swing.JList();
        lblProjectLeaderName = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jbnLäggTillAnställd = new javax.swing.JButton();
        combBytLedare = new javax.swing.JComboBox();
        combAndraAnstalld = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        combSetLeader = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextProjektNamn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelAnställd = new javax.swing.JPanel();
        labelcombanstalld = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelÖverskrift.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LabelÖverskrift.setText("Lägg till projekt");

        jLabel8.setText("Valt Projekt");

        jLabel7.setText("Projektnamn:");

        LblProjektNamn.setText("<none>");

        combChangeProject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combChangeProject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combChangeProjectItemStateChanged(evt);
            }
        });

        jLabel9.setText("Ledare:");

        jLabel11.setText("Jobbar i projekt:");

        jScrollPane2.setViewportView(jListProjektJobbare);

        lblProjectLeaderName.setText("<none>");

        jButton7.setText("Ta bort");

        jbnLäggTillAnställd.setText("lägg till");
        jbnLäggTillAnställd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnLäggTillAnställdActionPerformed(evt);
            }
        });

        combBytLedare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combAndraAnstalld.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combAndraAnstalld.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combAndraAnstalldItemStateChanged(evt);
            }
        });
        combAndraAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combAndraAnstalldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(combChangeProject, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(combBytLedare, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combAndraAnstalld, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblProjektNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProjectLeaderName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jbnLäggTillAnställd)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton7))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 45, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(combChangeProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblProjektNamn)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblProjectLeaderName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbnLäggTillAnställd)
                            .addComponent(jButton7)
                            .addComponent(combAndraAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(combBytLedare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        combSetLeader.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setText("lägg till");

        jLabel5.setText("Sätt ledare");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(combSetLeader, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combSetLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTextProjektNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProjektNamnActionPerformed(evt);
            }
        });

        jLabel3.setText("Namn:");

        jButton1.setText("lägg till");

        jLabel2.setText("Nytt projekt");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextProjektNamn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        labelcombanstalld.setText("Välj en anställd");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PanelAnställdLayout = new javax.swing.GroupLayout(PanelAnställd);
        PanelAnställd.setLayout(PanelAnställdLayout);
        PanelAnställdLayout.setHorizontalGroup(
            PanelAnställdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnställdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAnställdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelcombanstalld)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAnställdLayout.setVerticalGroup(
            PanelAnställdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnställdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelcombanstalld)
                .addGap(18, 18, 18)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jButton2.setText("lägg till projekt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(LabelÖverskrift))
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelAnställd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LabelÖverskrift)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelAnställd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combAndraAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combAndraAnstalldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combAndraAnstalldActionPerformed

    private void jTextProjektNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProjektNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProjektNamnActionPerformed

    private void combAndraAnstalldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combAndraAnstalldItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combAndraAnstalldItemStateChanged

    private void combChangeProjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combChangeProjectItemStateChanged
      displayProjectInfo();
    }//GEN-LAST:event_combChangeProjectItemStateChanged

    private void jbnLäggTillAnställdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnLäggTillAnställdActionPerformed
        
        if(combAndraAnstalld.getSelectedItem().toString().equals("<none>"))
        {
            JOptionPane.showMessageDialog(rootPane, "Välj en anställd");
            return;
        }
        boolean finnsI = false;
        ListModel model = jListProjektJobbare.getModel();
        for( int i = 0; i < model.getSize(); i++)
        {
            if(model.getElementAt(i).toString().equals(combAndraAnstalld.getSelectedItem().toString()))
            {
                finnsI = true;
            }
            
        }
        if (finnsI)
        {
           JOptionPane.showMessageDialog(rootPane, "Den anställde jobbar redan i projektet");
           return;
        }
        String valdAnstalld = combAndraAnstalld.getSelectedItem().toString();
        String anvnamn = valdAnstalld.substring((valdAnstalld.indexOf("(") + 1), 
                                                       valdAnstalld.indexOf(")"));
        String valtProjekt = combChangeProject.getSelectedItem().toString();
        
        String aid = konverteraTillAid(anvnamn);
        String sid = konverteraTillSid(valtProjekt);
        
        String query = "insert into ARBETAR_I (AID, SID) values('" + aid + "','" + sid + "');";
        
        try {
            databasen.insert(query);
        } catch (InfException ex) {
        }
        setProjectlist();
       
    }//GEN-LAST:event_jbnLäggTillAnställdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laggTillProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laggTillProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laggTillProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laggTillProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laggTillProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelÖverskrift;
    private javax.swing.JLabel LblProjektNamn;
    private javax.swing.JPanel PanelAnställd;
    private javax.swing.JComboBox combAndraAnstalld;
    private javax.swing.JComboBox combBytLedare;
    private javax.swing.JComboBox combChangeProject;
    private javax.swing.JComboBox combSetLeader;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListProjektJobbare;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextProjektNamn;
    private javax.swing.JButton jbnLäggTillAnställd;
    private javax.swing.JLabel labelcombanstalld;
    private javax.swing.JLabel lblProjectLeaderName;
    // End of variables declaration//GEN-END:variables

    private void setFyllProject() {
        
        String query = "SELECT BETECKNING FROM SPELPROJEKT ORDER BY BETECKNING ASC";
        try {
            
            combChangeProject.removeAllItems();
            ArrayList<String> projekten = databasen.fetchColumn(query);
            combChangeProject.addItem("Byt Projekt <inget valt>");
            for(String projekt : projekten)
            {
                combChangeProject.addItem(projekt);
                
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    private void setFyllLedare() {
        String query = "SELECT ANSTALLD.NAMN FROM PROJEKTLEDARE\n" +
                       "JOIN ANSTALLD ON PROJEKTLEDARE.AID = ANSTALLD.AID\n" +
                       "ORDER BY NAMN ASC";
        try {
            
            combSetLeader.removeAllItems();
            ArrayList<String> ledarLista = databasen.fetchColumn(query);
            combSetLeader.addItem("<none>");
            for(String ledare : ledarLista)
            {
                combSetLeader.addItem(ledare);
                
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    private void fyllAnstalld() {
       String query = "SELECT ANSTALLD.NAMN, ANSTALLD.ANVNAMN FROM ANSTALLD ORDER BY NAMN ASC";
        try {
            
            combAndraAnstalld.removeAllItems();
            ArrayList<HashMap<String,String>> anstalldLista = new ArrayList<>();
            anstalldLista = databasen.fetchRows(query);
            combAndraAnstalld.addItem("<none>");
            for(HashMap<String,String> anstalld : anstalldLista)
            {
                
                String enAnstalld = anstalld.get("NAMN")+ " (" + anstalld.get("ANVNAMN") + ")";
                combAndraAnstalld.addItem(enAnstalld);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    private void fyllLedare() {
       String query = "SELECT ANSTALLD.NAMN FROM PROJEKTLEDARE\n" +
                       "JOIN ANSTALLD ON PROJEKTLEDARE.AID = ANSTALLD.AID\n" +
                       "ORDER BY NAMN ASC";
        try {
            
            combBytLedare.removeAllItems();
            ArrayList<String> ledarLista = databasen.fetchColumn(query);
            combBytLedare.addItem("<Välj Ledare>");
            for(String ledare : ledarLista)
            {
                combBytLedare.addItem(ledare);
                
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    
    private void displayProjectInfo()
    {
        jListProjektJobbare.setModel(new DefaultListModel());
       if( setProjectNamelabel())
       {
         setProjectLeaderName();
         setProjectlist();
       }
        
        
           
    }

    private boolean setProjectNamelabel() {
        
        int selectedIndex = combChangeProject.getSelectedIndex();
        if (selectedIndex == -1) {
            return false;
        }
        if (selectedIndex == 0) {
            LblProjektNamn.setText("<none>");
            lblProjectLeaderName.setText("<none>");
            return false;
        }
        String selectedProject = combChangeProject.getSelectedItem().toString();
        LblProjektNamn.setText(selectedProject);
        return true;
       
    }

    private void setProjectLeaderName() 
    {
        try {
            String spelprojekt = combChangeProject.getSelectedItem().toString();
            String query = "SELECT ANSTALLD.NAMN FROM PROJEKTLEDARE " +
                    "JOIN ANSTALLD ON PROJEKTLEDARE.AID = ANSTALLD.AID " +
                    "JOIN SPELPROJEKT ON PROJEKTLEDARE.AID = SPELPROJEKT.AID "
                    + "WHERE SPELPROJEKT.BETECKNING = '" + spelprojekt + "'";
            
            String ledare = databasen.fetchSingle(query);
            if(ledare != null){
            lblProjectLeaderName.setText(ledare);
            }
            
        } catch (InfException ex) {
        }
    }

    private void setProjectlist() 
    {
    try {
        DefaultListModel DLM = new DefaultListModel();
        String spelprojekt = combChangeProject.getSelectedItem().toString();
        String query = "SELECT ANSTALLD.NAMN, ANSTALLD.ANVNAMN FROM ANSTALLD join ARBETAR_I on ANSTALLD.AID = ARBETAR_I.AID"
                     + " JOIN SPELPROJEKT on ARBETAR_I.SID = SPELPROJEKT.SID "
                     + "WHERE SPELPROJEKT.BETECKNING = '" + spelprojekt + "'";
            ArrayList<HashMap<String,String>> anstallda = new ArrayList<>();
            anstallda = databasen.fetchRows(query);
            for(HashMap<String,String> anstalld : anstallda)
            {
               String enAnstalld = anstalld.get("NAMN")+ " (" + anstalld.get("ANVNAMN") + ")";
               DLM.addElement(enAnstalld);
            }
            jListProjektJobbare.setModel(DLM);
        } 
    catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "bajs!" + ex.getMessage());
        }

    }
    private String konverteraTillAid(String anvNamn)
    {
        
        String aid = "";
        
       
        String query = "SELECT AID FROM ANSTALLD WHERE ANVNAMN = '" + anvNamn + "'";
        try{
            aid = databasen.fetchSingle(query);
        }
        catch(InfException ex)
        {
            System.out.println("BLÄV FÄL!");
        }
        
        
        return aid;
    }
    private String konverteraTillSid(String valtProject)
    { 
        String sid = "";
        try {
           
            String query = "SELECT SPELPROJEKT.SID FROM SPELPROJEKT where BETECKNING = '" + valtProject + "'";
            sid = databasen.fetchSingle(query);
            }
            catch (InfException ex) 
             {
             }
        return sid;
            
     } 
    
}